In [1]:
import pandas as pd
import numpy as np

In [3]:
see = pd.read_csv('earthquake data/all_month.csv')
see.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2020-06-25T19:30:37.170Z,38.834499,-122.805832,2.10,0.56,md,6.0,85.0,0.01157,0.01,...,2020-06-25T19:32:13.069Z,"7km W of Cobb, CA",earthquake,0.49,1.64,NaN,1.0,automatic,nc,nc
1,2020-06-25T19:27:39.240Z,36.456500,-117.962500,4.51,1.96,ml,21.0,140.0,0.09631,0.16,...,2020-06-25T19:31:17.953Z,"17km SE of Lone Pine, CA",earthquake,0.38,1.48,0.167,26.0,automatic,ci,ci
2,2020-06-25T19:25:46.030Z,36.456000,-117.959167,4.13,1.75,ml,17.0,152.0,0.09887,0.18,...,2020-06-25T19:29:25.029Z,"18km SE of Lone Pine, CA",earthquake,0.74,1.72,0.156,23.0,automatic,ci,ci
3,2020-06-25T19:24:40.350Z,36.459833,-117.964167,5.80,1.71,ml,14.0,157.0,0.09562,0.21,...,2020-06-25T19:28:20.023Z,"17km SE of Lone Pine, CA",earthquake,0.83,2.14,0.146,20.0,automatic,ci,ci
4,2020-06-25T19:16:22.640Z,35.580000,-117.392167,7.22,0.93,ml,10.0,172.0,0.05745,0.14,...,2020-06-25T19:19:58.893Z,"20km S of Trona, CA",earthquake,0.72,0.52,0.143,9.0,automatic,ci,ci

In [4]:
see_earth = see[['time','latitude','longitude']]

In [5]:
see_earth.head()

                       time   latitude   longitude
0  2020-06-25T19:30:37.170Z  38.834499 -122.805832
1  2020-06-25T19:27:39.240Z  36.456500 -117.962500
2  2020-06-25T19:25:46.030Z  36.456000 -117.959167
3  2020-06-25T19:24:40.350Z  36.459833 -117.964167
4  2020-06-25T19:16:22.640Z  35.580000 -117.392167

In [6]:
li = see_earth['time'].tolist()

In [7]:
# Seperate the day, month, and year into seperate lists.
def date_ordering(dates):
    year = []
    month = []
    day = []
    for l in li:
        l = str(l)
        str_date = l.split('-')
        str_date = list(str_date)
        day.append(int("".join(str_date[2][:2]))) 
        year.append(int("".join(str_date[0])))
        month.append(int("".join(str_date[1])))
    return(year, month, day)

year, month, day =  date_ordering(li)

In [8]:
see_earth['year'] = year
see_earth['month'] = month
see_earth['day'] = day

C:\Users\Kenechi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Kenechi\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Kenechi\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [9]:
see_earth.head()

                       time   latitude   longitude  year  month  day
0  2020-06-25T19:30:37.170Z  38.834499 -122.805832  2020      6   25
1  2020-06-25T19:27:39.240Z  36.456500 -117.962500  2020      6   25
2  2020-06-25T19:25:46.030Z  36.456000 -117.959167  2020      6   25
3  2020-06-25T19:24:40.350Z  36.459833 -117.964167  2020      6   25
4  2020-06-25T19:16:22.640Z  35.580000 -117.392167  2020      6   25

In [10]:
see_earth.drop(['time'], axis = 1, inplace =True)
see_earth.head()

C:\Users\Kenechi\anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

    latitude   longitude  year  month  day
0  38.834499 -122.805832  2020      6   25
1  36.456500 -117.962500  2020      6   25
2  36.456000 -117.959167  2020      6   25
3  36.459833 -117.964167  2020      6   25
4  35.580000 -117.392167  2020      6   25